Introduce repository dispatch event in update workflow
This commit introduces a repository dispatch event to trigger the cruft-update GitHub workflow manually. Also added a "Check for conflict markers" step in update checker workflow for different project templates including Rust, Terraform and Python. This step checks for merge conflict markers and prompts for manual resolution when conflict markers are detected. Furthermore, 'auto-merge' labels are now added to the automatically created PRs when new updates are detected with Cruft.

diff --git a/.github/workflows/cruft-update_checker.yml b/.github/workflows/cruft-update_checker.yml
--- a/.github/workflows/cruft-update_checker.yml
+++ b/.github/workflows/cruft-update_checker.yml
@@ -21,3 +21,15 @@ jobs:
               echo "Error: Please resolve these conflicts manually."
               exit 1
           fi
+
+      - name: Check for conflict markers
+        run: |
+          conflict_files=$(grep -rlE '<<<<<<<|=======|>>>>>>>' . --exclude-dir=.github) || true
+          if [[ ! -z "$conflict_files" ]]; then
+            echo "Error: Found files with conflict markers:"
+            echo "$conflict_files"
+            echo "Please resolve these conflicts manually."
+            exit 1
+          else
+            echo "No conflict markers found."
+          fi
